#!/usr/bin/env Rscript

require(methods)
require(utils)
require("roxygen2")
roxygenize("skel", "../pkg/locClassData", unlink.target=TRUE)

warn <- warnings()
if (!is.null(warn)) {
	cat("Warnings?\n")
	print(warn)
}
